import js from '@eslint/js'
import globals from 'globals'
import reactHooks from 'eslint-plugin-react-hooks'
import reactRefresh from 'eslint-plugin-react-refresh'
import tseslint from 'typescript-eslint'
import { defineConfig, globalIgnores } from 'eslint/config'

export default defineConfig([
  // *Client.ts files are generated by `stellar contract bindings typescript`
  // (regen: `npm run generate` in packages/*-client) — don't lint generator output.
  globalIgnores(['dist', 'src/lib/treasuryClient.ts', 'src/lib/registryClient.ts', 'src/lib/factoryClient.ts']),
  {
    files: ['**/*.{ts,tsx}'],
    extends: [
      js.configs.recommended,
      tseslint.configs.recommended,
      reactHooks.configs.flat.recommended,
      reactRefresh.configs.vite,
    ],
    languageOptions: {
      globals: globals.browser,
    },
  },
  // Playwright specs: fixtures destructure `{}` and name their setup param `use`,
  // which the React hook rules misread as a hook call — neither applies outside React.
  {
    files: ['tests/e2e/**/*.ts'],
    rules: {
      'no-empty-pattern': 'off',
      'react-hooks/rules-of-hooks': 'off',
    },
  },
])
